
import React, { useState } from 'react';
import { QuoteRequestLog } from '../types';
import { X, Calendar, MapPin, Trash2, Search, Monitor, Clock } from 'lucide-react';

interface AdminRequestLogModalProps {
  logs: QuoteRequestLog[];
  onDeleteLog: (id: string) => void;
  onClose: () => void;
}

const AdminRequestLogModal: React.FC<AdminRequestLogModalProps> = ({ logs, onDeleteLog, onClose }) => {
  const [searchTerm, setSearchTerm] = useState('');

  const filteredLogs = logs.filter(log => 
    log.customer.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    log.customer.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
    log.tripName.toLowerCase().includes(searchTerm.toLowerCase())
  ).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full flex flex-col h-[85vh] animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50 rounded-t-xl">
          <div>
            <h3 className="font-bold text-slate-800 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-emerald-600" />
              Incoming Quote Requests
            </h3>
            <p className="text-xs text-slate-500">Log of all quote requests generated by customers.</p>
          </div>
          <button onClick={onClose} className="p-1 hover:bg-slate-200 rounded-full transition-colors">
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>

        {/* Search */}
        <div className="p-4 border-b border-slate-100 bg-white">
            <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input 
                    type="text" 
                    placeholder="Search by customer name, email, or trip..." 
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="w-full pl-9 p-2.5 border border-slate-200 rounded-lg text-sm bg-slate-50 focus:bg-white focus:ring-2 focus:ring-emerald-500 outline-none text-slate-900"
                />
            </div>
        </div>

        {/* List */}
        <div className="flex-1 overflow-y-auto bg-slate-50 p-4">
            {filteredLogs.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-slate-400">
                    <p className="text-sm">No requests found matching your search.</p>
                </div>
            ) : (
                <div className="space-y-4">
                    {filteredLogs.map(log => (
                        <div key={log.id} className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h4 className="font-bold text-slate-800 text-sm">{log.customer.name}</h4>
                                    <div className="text-xs text-slate-500 flex flex-col gap-0.5 mt-1">
                                        <span>{log.customer.email}</span>
                                        <span>{log.customer.phone}</span>
                                        {log.customer.company && <span className="text-slate-400 font-medium">{log.customer.company}</span>}
                                    </div>
                                </div>
                                <div className="text-right">
                                    <div className="text-[10px] font-bold uppercase text-emerald-600 bg-emerald-50 px-2 py-1 rounded border border-emerald-100 mb-1 inline-block">
                                        {log.tripName}
                                    </div>
                                    <div className="text-[10px] text-slate-400 font-mono">
                                        {new Date(log.timestamp).toLocaleString()}
                                    </div>
                                </div>
                            </div>

                            {/* Constraints / Notes */}
                            {log.constraints && (
                                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 text-xs text-slate-600 mb-4 italic">
                                    "{log.constraints}"
                                </div>
                            )}

                            {/* Metadata Footer */}
                            <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-slate-100">
                                <div className="flex items-center gap-4 text-[10px] text-slate-400">
                                    <div className="flex items-center gap-1.5" title="Location">
                                        <MapPin className="w-3 h-3 text-slate-300" />
                                        {log.metadata.city}, {log.metadata.region} ({log.metadata.country})
                                    </div>
                                    <div className="flex items-center gap-1.5" title="IP Address">
                                        <Monitor className="w-3 h-3 text-slate-300" />
                                        {log.metadata.ip}
                                    </div>
                                    <div className="flex items-center gap-1.5" title="Timezone">
                                        <Clock className="w-3 h-3 text-slate-300" />
                                        {log.metadata.timezone}
                                    </div>
                                </div>
                                
                                <button 
                                    onClick={() => onDeleteLog(log.id)}
                                    className="text-slate-300 hover:text-rose-500 transition-colors p-1"
                                    title="Delete Log Entry"
                                >
                                    <Trash2 className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default AdminRequestLogModal;
